# PyUCX-AI Multi-Agent Framework Configuration

# OpenAI Configuration (required)
openai_api_key: ${OPENAI_API_KEY}
openai_model: "gpt-4o-mini"
temperature: 0.1

# Alternative: Azure OpenAI Configuration
# azure_openai_endpoint: "https://your-resource.openai.azure.com/"
# azure_openai_api_key: ${AZURE_OPENAI_API_KEY}
# azure_openai_api_version: "2024-02-15-preview"

# Framework Configuration
max_iterations: 200
enable_checkpoints: true
checkpoint_dir: "./checkpoints"

# Agent Configuration
enable_parallel_processing: false
batch_size: 5

# Logging Configuration  
log_level: "INFO"
log_file: "pyucx_ai.log"

# Output Configuration
output_dir: "./output"
save_intermediate_results: true

# Processing Configuration
timeout_seconds: 300
retry_attempts: 3
